export const MARKETPRODUCT = {
  SHOW_RESET: 'MARKETPRODUCT_SHOW_RESET',
  SHOW_SET_ERROR: 'MARKETPRODUCT_SHOW_SET_ERROR',
  SHOW_SET_RETRIEVED: 'MARKETPRODUCT_SHOW_SET_RETRIEVED',
  SHOW_TOGGLE_LOADING: 'MARKETPRODUCT_SHOW_TOGGLE_LOADING',

  LIST_RESET: 'MARKETPRODUCT_LIST_RESET',
  LIST_SET_ITEMS: 'MARKETPRODUCT_LIST_SET_ITEMS',
  LIST_SET_ERROR: 'MARKETPRODUCT_LIST_SET_ERROR',
  LIST_SET_VIEW: 'MARKETPRODUCT_LIST_SET_VIEW',
  LIST_TOGGLE_LOADING: 'MARKETPRODUCT_LIST_TOGGLE_LOADING'
}
