version: "3"

services:
  nuxt:
    container_name: markets_nuxt
    build:
      context: ../
      dockerfile: ./docker/nuxt/Dockerfile
    tty: true
    ports:
      - ${NUXT_PORT}:3000
    environment:
      - VIRTUAL_HOST=${NUXT_VHOST}
    restart: always
    command:
      "yarn run dev"
    volumes:
      - '../:/src'
    networks:
      application:
        aliases:
          - ${NUXT_VHOST}

networks:
  application:
    external:
      name: 'markets'
