version: '3.3'

services:
  php:
    image: kreciszd/markets_php:1.0
    container_name: markets_php
    build: backend/docker/php
    volumes:
      - './backend:/var/www/html:cached'
    depends_on:
      - postgres
    networks:
      - application

  proxy:
    container_name: markets_proxy
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - application

  nginx:
    image: kreciszd/markets_nginx:1.0
    container_name: markets_nginx
    build:
      context: ./backend/docker/nginx
      dockerfile: Dockerfile
    volumes:
      - './backend/public:/var/www/html/public:cached'
    ports:
      - ${PHP_PORT}:80
    environment:
      - VIRTUAL_HOST=${PHP_VHOST}
    depends_on:
      - php
    networks:
      application:
        aliases:
          - ${PHP_VHOST}

  postgres:
    container_name: markets_postgres
    image: postgres:10.8
    stdin_open: true
    tty: true
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: markets
      POSTGRES_USER: markets
      POSTGRES_PASSWORD: markets
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - application

  adminer:
    container_name: markets_adminer
    image: adminer
    depends_on:
      - postgres
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - application

  quasar:
    image: kreciszd/markets_quasar:1.0
    container_name: markets_quasar
    build:
      context: ./frontend
      dockerfile: docker/quasar/Dockerfile
    tty: true
    ports:
      - ${QUASAR_PORT}:8080
    environment:
      - VIRTUAL_HOST=${QUASAR_VHOST}
    restart: always
    command:
      "yarn run dev"
    volumes:
      - './frontend:/src'
    networks:
      application:
        aliases:
          - ${QUASAR_VHOST}
volumes:
  postgres:
    driver: local

networks:
  application:
    external:
      name: 'markets'
