doctrine:
  dbal:
    # configure these for your database server
    driver: pdo_pgsql
    server_version: 10.8
    url: '%env(resolve:DATABASE_URL)%'
    types:
      enum_unit_type: App\BusinessLogic\SharedLogic\Type\EnumUnitType
    mapping_types:
      enum_unit_type: string

  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App
    filters:
      softdeleteable:
        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
        enabled: true
