nexy_slack:

  # If you want to use an another httplug client service.
  http:
    client: httplug.client

  # The Slack API Incoming WebHooks URL.
  endpoint:             https://hooks.slack.com/services/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
  channel:              scraping
  username:             Scraper
  icon:                 null
  link_names:           false
  unfurl_links:         false
  unfurl_media:         true
  allow_markdown:       true
  markdown_in_attachments: []