version: 2
jobs:
  build_and_test:
    working_directory: ~/
    docker:
      - image: kreciszd/markets_php:1.0

#    steps:
#      - run:
workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test