version: '3.3'

services:
  php:
    container_name: markets_php
    build: php
    volumes:
      - '../:/var/www/html:cached'
    depends_on:
      - postgres
    networks:
      - application

  reverse_proxy:
    container_name: reverse_proxy
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - application

  nginx_backend:
    container_name: markets_backend_nginx
    build: nginx
    volumes:
      - '../public:/var/www/html/public:cached'
    ports:
      - ${PHP_PORT}:80
    environment:
      - VIRTUAL_HOST=${PHP_VHOST}
    depends_on:
      - php
    networks:
      application:
        aliases:
        - ${PHP_VHOST}

  postgres:
    container_name: markets_postgres
    image: postgres:10.8
    stdin_open: true
    tty: true
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: markets
      POSTGRES_USER: markets
      POSTGRES_PASSWORD: markets
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - application

  adminer:
    container_name: markets_adminer
    image: adminer
    depends_on:
      - postgres
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - application

volumes:
  postgres:
    driver: local

networks:
  application:
    external:
      name: 'markets'
